export const polarizado = {
  name: 'polarizado', title: 'Polarizado', type: 'document',
  fields: [
    { name: 'name', title: 'Nombre', type: 'string', validation: (Rule) => Rule.required() },
    { name: 'slug', title: 'Slug', type: 'slug', options: { source: 'name', maxLength: 96 }, validation: (Rule) => Rule.required() },
    { name: 'shortDescription', title: 'Descripción corta', type: 'text', rows: 3 },
    { name: 'fullDescription', title: 'Descripción completa', type: 'array', of: [{ type: 'block' }] },
    { name: 'mainImage', title: 'Imagen principal', type: 'image', options: { hotspot: true } },
    { name: 'gallery', title: 'Galería de imágenes', type: 'array', of: [{ type: 'image', options: { hotspot: true } }] },
    { name: 'category', title: 'Categoría', type: 'string' },
    { name: 'features', title: 'Características', type: 'array', of: [{ type: 'string' }] },
    { name: 'uvProtection', title: 'Protección UV', type: 'string' },
    { name: 'tones', title: 'Tonalidades disponibles', type: 'array', of: [{ type: 'string' }] },
    { name: 'heatReduction', title: 'Reducción de calor', type: 'string' },
    { name: 'securityLevel', title: 'Nivel de seguridad', type: 'string' },
    { name: 'price', title: 'Precio opcional', type: 'string' },
    { name: 'priceText', title: 'Texto de precio', type: 'string', initialValue: 'Consultar' },
    { name: 'featured', title: 'Producto destacado', type: 'boolean', initialValue: false },
    { name: 'order', title: 'Orden de aparición', type: 'number', initialValue: 100 },
    { name: 'active', title: 'Activo / visible', type: 'boolean', initialValue: true },
    { name: 'buttonText', title: 'Texto del botón', type: 'string', initialValue: 'Consultar' },
    { name: 'whatsappLink', title: 'Enlace de WhatsApp', type: 'url' },
  ],
}
